{% set name = "minimalf2py" %}
{% set version = "0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ../

build:
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  number: 1

requirements:
  build:
    - ninja                                  
    - pkg-config                             # [unix]
    - clang                                  # [win]
    # use flang as fortran compiler on windows (uses clang driver)
    - flang <18                              # [win]
    # use llvm linker for both of the above
    - lld                                    # [win]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('fortran') }}              # [unix]
  host:
    - compiler-rt                            # [win]
    - meson-python
    # limit this for now because incompatible changes
    # have accumulated in meson_dev channel for 1.4+
    - meson <1.4                             # [win]
    - python
    - python-build
    - numpy
    - pip
    - packaging >=20.0
  run:
    - python
    - numpy

test:
  requires:
    - pytest
  imports:
    - minimalf2py
  commands:
    - pytest -v --pyargs minimalf2py

extra:
  recipe-maintainers:
    - brian-rose
