{% set name = "minimalf2py" %}
{% set version = "0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ../

build:
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [win and py<30]
  number: 1

requirements:
  build:
    - {{ compiler('fortran') }}  # [not win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ compiler('c') }}
  host:
    - libpython  # [win]
    - python
    - setuptools
    - pip
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}
    #- scipy  # uncommenting this line causes conda-build to hang forever on Mac OS

test:
  requires:
    - pytest
  imports:
    - minimalf2py
  commands:
    - pytest -v --pyargs minimalf2py.tests

extra:
  recipe-maintainers:
    - brian-rose
