name: Conda-build

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:

  conda-build-test:
    name: ${{ matrix.os }} py${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}-latest
    defaults:
      run:
        shell: ${{ matrix.shell }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8"]
        os: [Ubuntu, macOS, Windows]
        include:
          - os: Ubuntu
            shell: bash -l {0}
          - os: macOS
            shell: bash -l {0}
          - os: Windows
            shell: powershell

    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          python-version: ${{ matrix.python-version }}
          channels: conda-forge
      - name: Install conda-build
        run: |
          conda install conda-build
      - name: Run conda-build
        run: |
          conda-build -c conda-forge conda-recipe
